name: learn-github-actions
run-name: ${{github.actor}} is learning GihubActions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - users: action/checkout@v3
      - users: action/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v